# makefile for run code
# version 1.0 by Gwangwon Kim

what:
	@echo "	env       : Set environment and dependencies"
	@echo "	train     : Run model_training.py - for training models"

env:
	pip install -r "requirements.txt"

train:
	python3 "model_training.py"